# Generated by Django 4.2.2 on 2023-06-29 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_category_conference_date_conference_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='conference',
            name='conf_logo',
            field=models.ImageField(null=True, upload_to='conferences/logo/'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='conference',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='venue',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
